# Generated by Django 5.2 on 2025-06-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userid",
                    models.CharField(max_length=10, unique=True, verbose_name="使用者編號"),
                ),
                ("username", models.CharField(max_length=10, verbose_name="使用者名稱")),
            ],
            options={"ordering": ["userid"],},
        ),
        migrations.CreateModel(
            name="StockChecker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="執行盤點的人員"
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(max_length=20, unique=True, verbose_name="財編"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="品名")),
                (
                    "accessories",
                    models.TextField(
                        blank=True, default="暫無附件", null=True, verbose_name="附件"
                    ),
                ),
                (
                    "unit_price",
                    models.PositiveIntegerField(default=0, verbose_name="單價"),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="廠牌"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="型號"
                    ),
                ),
                (
                    "origin_country",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="國別"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="序號"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="存放處所"
                    ),
                ),
                (
                    "lifespan_years",
                    models.PositiveIntegerField(default=0, verbose_name="使用年限"),
                ),
                (
                    "funding_source",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="經費來源"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("財產", "財產"), ("非消耗品", "非消耗品")],
                        max_length=20,
                        verbose_name="財產類別",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="購入日期"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.assetuserprofile",
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={"ordering": ["asset_code", "name", "user", "purchase_date"],},
        ),
        migrations.AddField(
            model_name="assetuserprofile",
            name="stockchecker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.stockchecker",
                verbose_name="執行盤點的範圍",
            ),
        ),
        migrations.CreateModel(
            name="SystemUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="使用者名稱")),
                ("email", models.EmailField(max_length=254, verbose_name="使用者信箱")),
                ("password", models.CharField(max_length=20, verbose_name="使用者密碼")),
                (
                    "room",
                    models.CharField(max_length=20, null=True, verbose_name="實驗室之編號"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("系統管理者", "系統管理者"), ("一般使用者", "一般使用者")],
                        default="一般使用者",
                        max_length=10,
                        verbose_name="使用者權限",
                    ),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="帳號啟用")),
                (
                    "stockchecker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.stockchecker",
                        verbose_name="執行盤點的範圍",
                    ),
                ),
            ],
            options={"ordering": ["name", "enabled"],},
        ),
    ]
