# Generated by Django 5.2 on 2025-06-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[("財產", "財產"), ("非消耗品", "非消耗品")],
                max_length=20,
                verbose_name="財產類別",
            ),
        ),
    ]
