# Generated by Django 5.2 on 2025-05-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="user",
        ),
        migrations.RemoveField(
            model_name="storagelocation",
            name="Lid",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="使用者信箱"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="帳戶啟用"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="password",
            field=models.CharField(max_length=128, verbose_name="使用者密碼"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="使用者電話"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="userid",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="使用者編號"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=10, verbose_name="使用者名稱"),
        ),
    ]
