# Generated by Django 5.2 on 2025-06-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="systemuser", name="room",),
    ]
