# Generated by Django 5.2 on 2025-06-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_alter_asset_asset_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="AssetUserProfile",
        ),
    ]
