# Generated by Django 5.2 on 2025-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_remove_asset_user_remove_storagelocation_lid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="model",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="型號"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="序號"
            ),
        ),
    ]
