# Generated by Django 5.2 on 2025-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_rename_userprofile_assetuserprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="使用者名稱")),
                ("email", models.EmailField(max_length=254, verbose_name="使用者信箱")),
                (
                    "password",
                    models.CharField(max_length=20, verbose_name="使用者名稱"),
                ),
                ("room", models.TextField(null=True, verbose_name="實驗室之編號")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("系統管理者", "系統管理者"),
                            ("一般使用者", "一般使用者"),
                        ],
                        default="一般使用者",
                        max_length=10,
                        verbose_name="使用者權限",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="帳號啟用"),
                ),
            ],
        ),
    ]
