# Generated by Django 5.2 on 2025-06-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_systemuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="password",
            field=models.CharField(max_length=20, verbose_name="使用者密碼"),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="room",
            field=models.CharField(
                max_length=20, null=True, verbose_name="實驗室之編號"
            ),
        ),
    ]
