# Generated by Django 5.2 on 2025-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_systemuser_password_alter_systemuser_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='funding_source',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='經費來源'),
        ),
    ]
